// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4F_SEdg1fMaOWNWpmwmrxlxKWZLF7pnY',
    appId: '1:389618955282:web:ae77c39f852161478254cb',
    messagingSenderId: '389618955282',
    projectId: 'mecanicsolution-9bf19',
    authDomain: 'mecanicsolution-9bf19.firebaseapp.com',
    storageBucket: 'mecanicsolution-9bf19.appspot.com',
    measurementId: 'G-WMZZ0CL9T2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT0T_H8WXdZEwNU66FVgrluGd7uEkY8S8',
    appId: '1:389618955282:android:bf625e30453389988254cb',
    messagingSenderId: '389618955282',
    projectId: 'mecanicsolution-9bf19',
    storageBucket: 'mecanicsolution-9bf19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr-SSitexLDU7Rl-aLVa3UnnToYwqpqOE',
    appId: '1:389618955282:ios:cd1b3c30fd312ccc8254cb',
    messagingSenderId: '389618955282',
    projectId: 'mecanicsolution-9bf19',
    storageBucket: 'mecanicsolution-9bf19.appspot.com',
    iosBundleId: 'com.codigocorrecto.crudMecanicsolution',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr-SSitexLDU7Rl-aLVa3UnnToYwqpqOE',
    appId: '1:389618955282:ios:43e835c7002c371a8254cb',
    messagingSenderId: '389618955282',
    projectId: 'mecanicsolution-9bf19',
    storageBucket: 'mecanicsolution-9bf19.appspot.com',
    iosBundleId: 'com.codigocorrecto.crudMecanicsolution.RunnerTests',
  );
}
